# Setup
title:               Aranya Documentation
tagline:             'An overview of the Aranya project'
description:         'Aranya is an access governance and secure data exchange platform for organizations to control their critical data and services.'
url:                 https://aranya-project.github.io/aranya-docs
project-repo: https://github.com/aranya-project/aranya
baseurl:             ''
permalink:           pretty

# Excludes
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

