# Setup
title:               Aranya Documentation
tagline:             'An overview of the Aranya project'
description:         'Aranya is an access governance and secure data exchange platform for organizations to control their critical data and services.'
url:                 https://aranya-project.github.io/aranya-docs/
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
