kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
# Exclude files and directories
exclude: []
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - aranya-overview
  - aranya-beta
  - afc
  - afc-crypto
  - aranya-sessions-notes
  - graph
  - model
  -  open-sync
  - policy-v1
  - policy-v2
  - skip-list
  - sync

