kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
# Exclude files and directories
exclude: []
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
