kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
# Exclude files and directories
exclude: []
title: Aranya Documentation
description: An overview of the Aranya project
# theme: jekyll-theme-minimal
remote_theme: poole/lanyon@main
# sidebar:
#   - aranya-overview
#   - aranya-beta
#   - afc
#   - afc-crypto
#   - aranya-sessions-notes
#   - graph
#   - model
#   - open-sync
#   - policy-v1
#   - policy-v2
#   - skip-list
#   - sync
